/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Aplicacao.ControladorBiblioteca;
import javax.swing.JOptionPane;

/**
 *
 * @author Júlia
 */
public class TelaLoginGerente extends javax.swing.JFrame {

    /**
     * Creates new form TelaLoginGerente
     */
    public TelaLoginGerente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelLoginGerente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtLoginGerenteEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtLoginGerenteSenha = new javax.swing.JPasswordField();
        BotaoLoginGerente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loggar como gerente");
        setResizable(false);

        jLabel1.setText("Email");

        TxtLoginGerenteEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLoginGerenteEmailActionPerformed(evt);
            }
        });

        jLabel2.setText("Senha");

        TxtLoginGerenteSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLoginGerenteSenhaActionPerformed(evt);
            }
        });

        BotaoLoginGerente.setText("Entrar");
        BotaoLoginGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLoginGerenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelLoginGerenteLayout = new javax.swing.GroupLayout(PainelLoginGerente);
        PainelLoginGerente.setLayout(PainelLoginGerenteLayout);
        PainelLoginGerenteLayout.setHorizontalGroup(
            PainelLoginGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLoginGerenteLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(PainelLoginGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotaoLoginGerente)
                    .addGroup(PainelLoginGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtLoginGerenteEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                        .addComponent(TxtLoginGerenteSenha)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        PainelLoginGerenteLayout.setVerticalGroup(
            PainelLoginGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLoginGerenteLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtLoginGerenteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtLoginGerenteSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(BotaoLoginGerente)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelLoginGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(PainelLoginGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtLoginGerenteEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLoginGerenteEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLoginGerenteEmailActionPerformed

    private void TxtLoginGerenteSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLoginGerenteSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLoginGerenteSenhaActionPerformed

    private void BotaoLoginGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLoginGerenteActionPerformed
        String texto = TxtLoginGerenteEmail.getText();
        String senha = String.valueOf(TxtLoginGerenteSenha.getPassword());
        ControladorBiblioteca biblioteca = new ControladorBiblioteca(); //ajeitar isso aqui
        if(biblioteca.FazerLoginFuncionario(texto, senha) && biblioteca.VerificarSeEGerente(texto)){
            new TelaGerente().setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Acesso negado");
        }
    }//GEN-LAST:event_BotaoLoginGerenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLoginGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLoginGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLoginGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLoginGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLoginGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoLoginGerente;
    private javax.swing.JPanel PainelLoginGerente;
    private javax.swing.JTextField TxtLoginGerenteEmail;
    private javax.swing.JPasswordField TxtLoginGerenteSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
