/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author Júlia
 */
public class TelaFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaFuncionario
     */
    public TelaFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuFuncionario = new javax.swing.JMenuBar();
        AbaLivroFuncionario = new javax.swing.JMenu();
        AbaEmprestimoFuncionario = new javax.swing.JMenu();
        AbaDevolucaoFuncionario = new javax.swing.JMenu();
        AbaPagarMultaFuncionario = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AbaLivroFuncionario.setText("Registrar Livro");
        AbaLivroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbaLivroFuncionarioActionPerformed(evt);
            }
        });
        MenuFuncionario.add(AbaLivroFuncionario);

        AbaEmprestimoFuncionario.setText("Fazer empréstimo");
        AbaEmprestimoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbaEmprestimoFuncionarioActionPerformed(evt);
            }
        });
        MenuFuncionario.add(AbaEmprestimoFuncionario);

        AbaDevolucaoFuncionario.setText("Fazer devolução");
        AbaDevolucaoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbaDevolucaoFuncionarioActionPerformed(evt);
            }
        });
        MenuFuncionario.add(AbaDevolucaoFuncionario);

        AbaPagarMultaFuncionario.setText("Fazer pagamento de multa");
        AbaPagarMultaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbaPagarMultaFuncionarioActionPerformed(evt);
            }
        });
        MenuFuncionario.add(AbaPagarMultaFuncionario);

        setJMenuBar(MenuFuncionario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AbaLivroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbaLivroFuncionarioActionPerformed
        // TODO add your handling code here:
        new TelaLivro().setVisible(true);
    }//GEN-LAST:event_AbaLivroFuncionarioActionPerformed

    private void AbaEmprestimoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbaEmprestimoFuncionarioActionPerformed
        // TODO add your handling code here:
        new TelaEmprestimo().setVisible(true);
    }//GEN-LAST:event_AbaEmprestimoFuncionarioActionPerformed

    private void AbaDevolucaoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbaDevolucaoFuncionarioActionPerformed
        // TODO add your handling code here:
        new TelaDevolucao().setVisible(true);
    }//GEN-LAST:event_AbaDevolucaoFuncionarioActionPerformed

    private void AbaPagarMultaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbaPagarMultaFuncionarioActionPerformed
        // TODO add your handling code here:
        new TelaPrecoMulta().setVisible(true);
    }//GEN-LAST:event_AbaPagarMultaFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AbaDevolucaoFuncionario;
    private javax.swing.JMenu AbaEmprestimoFuncionario;
    private javax.swing.JMenu AbaLivroFuncionario;
    private javax.swing.JMenu AbaPagarMultaFuncionario;
    private javax.swing.JMenuBar MenuFuncionario;
    // End of variables declaration//GEN-END:variables
}
