/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Aplicacao.ControladorBiblioteca;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author Júlia
 */
public class TelaCadastroFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroFuncionario
     */
    public TelaCadastroFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelCadastroLeitor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtCadastroFuncionarioNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        TxtCadastroFuncionarioEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtCadastroFuncionarioEndereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtCadastroFuncionarioTelefone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtCadastroFuncionarioCPF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtCadastroFuncionarioDia = new javax.swing.JTextField();
        TxtCadastroFuncionarioMes = new javax.swing.JTextField();
        TxtCadastroFuncionarioAno = new javax.swing.JTextField();
        TxtCadastroFuncionarioSenha = new javax.swing.JPasswordField();
        BotaoCadastroFuncionario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar como Funcionario");

        jLabel1.setText("Nome ");

        TxtCadastroFuncionarioNome.setText("Seu nome completo");
        TxtCadastroFuncionarioNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCadastroFuncionarioNomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Endereco");

        jTextField2.setText("jTextField1");

        jLabel4.setText("Email");

        jLabel5.setText("Telefone");

        jLabel6.setText("CPF");

        jLabel7.setText("Senha");

        jLabel8.setText("Data de Nascimento");

        TxtCadastroFuncionarioDia.setText("Dia");
        TxtCadastroFuncionarioDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCadastroFuncionarioDiaActionPerformed(evt);
            }
        });

        TxtCadastroFuncionarioMes.setText("Mês");
        TxtCadastroFuncionarioMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCadastroFuncionarioMesActionPerformed(evt);
            }
        });

        TxtCadastroFuncionarioAno.setText("Ano");

        BotaoCadastroFuncionario.setText("Cadastrar");
        BotaoCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastroFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelCadastroLeitorLayout = new javax.swing.GroupLayout(PainelCadastroLeitor);
        PainelCadastroLeitor.setLayout(PainelCadastroLeitorLayout);
        PainelCadastroLeitorLayout.setHorizontalGroup(
            PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastroLeitorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCadastroFuncionarioTelefone)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelCadastroLeitorLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCadastroFuncionarioNome, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(TxtCadastroFuncionarioEmail)
                    .addComponent(TxtCadastroFuncionarioEndereco)
                    .addComponent(TxtCadastroFuncionarioCPF)
                    .addGroup(PainelCadastroLeitorLayout.createSequentialGroup()
                        .addComponent(TxtCadastroFuncionarioDia, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtCadastroFuncionarioMes, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtCadastroFuncionarioAno, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TxtCadastroFuncionarioSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(BotaoCadastroFuncionario)
                .addGap(21, 21, 21))
            .addGroup(PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PainelCadastroLeitorLayout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(122, Short.MAX_VALUE)))
        );
        PainelCadastroLeitorLayout.setVerticalGroup(
            PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastroLeitorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtCadastroFuncionarioNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtCadastroFuncionarioEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtCadastroFuncionarioEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtCadastroFuncionarioTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtCadastroFuncionarioCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCadastroFuncionarioDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCadastroFuncionarioMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCadastroFuncionarioAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCadastroFuncionarioSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoCadastroFuncionario))
                .addGap(13, 13, 13))
            .addGroup(PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PainelCadastroLeitorLayout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(310, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelCadastroLeitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCadastroFuncionarioNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCadastroFuncionarioNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCadastroFuncionarioNomeActionPerformed

    private void TxtCadastroFuncionarioDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCadastroFuncionarioDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCadastroFuncionarioDiaActionPerformed

    private void TxtCadastroFuncionarioMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCadastroFuncionarioMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCadastroFuncionarioMesActionPerformed

    private void BotaoCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastroFuncionarioActionPerformed
        // TODO add your handling code here:
        String nome = TxtCadastroFuncionarioNome.getText();
        String email = TxtCadastroFuncionarioEmail.getText();
        String endereco = TxtCadastroFuncionarioEndereco.getText();
        String telefone = TxtCadastroFuncionarioTelefone.getText();
        String CPF = TxtCadastroFuncionarioCPF.getText();
        String senha = String.valueOf(TxtCadastroFuncionarioSenha.getPassword());
        int dia = Integer.parseInt(TxtCadastroFuncionarioDia.getText());
        int mes = Integer.parseInt(TxtCadastroFuncionarioMes.getText());
        int ano = Integer.parseInt(TxtCadastroFuncionarioAno.getText());
        LocalDate dataNascimento = LocalDate.of(ano, mes, dia);
        ControladorBiblioteca biblioteca = new ControladorBiblioteca(); //ajeitar isso aqui
        if(biblioteca.FazerCadastroFuncionario(nome, email, CPF, senha, telefone, endereco, dataNascimento)){
            new TelaFuncionario().setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "O cadastro não pode ser concluído");
        }
    }//GEN-LAST:event_BotaoCadastroFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastroFuncionario;
    private javax.swing.JPanel PainelCadastroLeitor;
    private javax.swing.JTextField TxtCadastroFuncionarioAno;
    private javax.swing.JTextField TxtCadastroFuncionarioCPF;
    private javax.swing.JTextField TxtCadastroFuncionarioDia;
    private javax.swing.JTextField TxtCadastroFuncionarioEmail;
    private javax.swing.JTextField TxtCadastroFuncionarioEndereco;
    private javax.swing.JTextField TxtCadastroFuncionarioMes;
    private javax.swing.JTextField TxtCadastroFuncionarioNome;
    private javax.swing.JPasswordField TxtCadastroFuncionarioSenha;
    private javax.swing.JTextField TxtCadastroFuncionarioTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
