/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Aplicacao.*;

import java.awt.List;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Júlia
 */
public class TelaLivro extends javax.swing.JFrame {

    /**
     * Creates new form TelaLivro
     */
    public TelaLivro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelCadastroLeitor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtRegistroLivroTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        TxtRegistroLivroISBN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtRegistroLivroEdicao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtRegistroLivroAutores = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BotaoRegistroLivro = new javax.swing.JButton();
        COMEDIA = new javax.swing.JCheckBox();
        DRAMA = new javax.swing.JCheckBox();
        FANTASIA = new javax.swing.JCheckBox();
        THRILLER = new javax.swing.JCheckBox();
        TERROR = new javax.swing.JCheckBox();
        ROMANCE = new javax.swing.JCheckBox();
        POLICIAL = new javax.swing.JCheckBox();
        DISTOPIA = new javax.swing.JCheckBox();
        ACAO = new javax.swing.JCheckBox();
        AVENTURA = new javax.swing.JCheckBox();
        BIBLIOGRAFIA = new javax.swing.JCheckBox();
        AUTOAJUDA = new javax.swing.JCheckBox();
        TRUECRIME = new javax.swing.JCheckBox();
        DIDATICO = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Livro");
        setResizable(false);

        PainelCadastroLeitor.setToolTipText("");

        jLabel1.setText("Tiutlo");

        TxtRegistroLivroTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRegistroLivroTituloActionPerformed(evt);
            }
        });

        jLabel3.setText("Edição");

        jTextField2.setText("jTextField1");

        jLabel4.setText("ISBN");

        jLabel5.setText("Autor(es)");

        jLabel6.setText("Gêneros");

        BotaoRegistroLivro.setText("Registrar");
        BotaoRegistroLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRegistroLivroActionPerformed(evt);
            }
        });

        COMEDIA.setText("COMÉDIA");
        COMEDIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMEDIAActionPerformed(evt);
            }
        });

        DRAMA.setText("DRAMA");
        DRAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DRAMAActionPerformed(evt);
            }
        });

        FANTASIA.setText("FANTASIA");

        THRILLER.setText("THRILLER");

        TERROR.setText("TERROR");

        ROMANCE.setText("ROMANCE");
        ROMANCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ROMANCEActionPerformed(evt);
            }
        });

        POLICIAL.setText("POLICIAL");

        DISTOPIA.setText("DISTOPIA");

        ACAO.setText("AÇÃO");

        AVENTURA.setText("AVENTURA");

        BIBLIOGRAFIA.setText("BIBLIOGRAFIA");
        BIBLIOGRAFIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIBLIOGRAFIAActionPerformed(evt);
            }
        });

        AUTOAJUDA.setText("AUTOAJUDA");

        TRUECRIME.setText("TRUECRIME");

        DIDATICO.setText("DIDÁTICO");

        javax.swing.GroupLayout PainelCadastroLeitorLayout = new javax.swing.GroupLayout(PainelCadastroLeitor);
        PainelCadastroLeitor.setLayout(PainelCadastroLeitorLayout);
        PainelCadastroLeitorLayout.setHorizontalGroup(
            PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastroLeitorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelCadastroLeitorLayout.createSequentialGroup()
                        .addGroup(PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtRegistroLivroAutores)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PainelCadastroLeitorLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtRegistroLivroTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(TxtRegistroLivroISBN)
                            .addComponent(TxtRegistroLivroEdicao))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PainelCadastroLeitorLayout.createSequentialGroup()
                        .addComponent(COMEDIA, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ROMANCE, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BIBLIOGRAFIA)
                        .addGap(110, 110, 110))
                    .addGroup(PainelCadastroLeitorLayout.createSequentialGroup()
                        .addGroup(PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelCadastroLeitorLayout.createSequentialGroup()
                                .addComponent(TERROR, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AVENTURA, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotaoRegistroLivro))
                            .addGroup(PainelCadastroLeitorLayout.createSequentialGroup()
                                .addGroup(PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PainelCadastroLeitorLayout.createSequentialGroup()
                                        .addComponent(THRILLER, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ACAO, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DIDATICO, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PainelCadastroLeitorLayout.createSequentialGroup()
                                        .addComponent(FANTASIA, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DISTOPIA, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TRUECRIME, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PainelCadastroLeitorLayout.createSequentialGroup()
                                        .addComponent(DRAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(POLICIAL, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AUTOAJUDA)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PainelCadastroLeitorLayout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(128, Short.MAX_VALUE)))
        );
        PainelCadastroLeitorLayout.setVerticalGroup(
            PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastroLeitorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtRegistroLivroTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtRegistroLivroISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtRegistroLivroEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtRegistroLivroAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(COMEDIA)
                    .addComponent(ROMANCE)
                    .addComponent(BIBLIOGRAFIA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DRAMA)
                    .addComponent(POLICIAL)
                    .addComponent(AUTOAJUDA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FANTASIA)
                    .addComponent(DISTOPIA)
                    .addComponent(TRUECRIME))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(THRILLER)
                    .addComponent(ACAO)
                    .addComponent(DIDATICO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TERROR)
                    .addComponent(AVENTURA)
                    .addComponent(BotaoRegistroLivro))
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PainelCadastroLeitorLayout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(310, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelCadastroLeitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtRegistroLivroTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRegistroLivroTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRegistroLivroTituloActionPerformed

    private void BotaoRegistroLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRegistroLivroActionPerformed
        // TODO add your handling code here:
        String titulo = TxtRegistroLivroTitulo.getText();
        String ISBN = TxtRegistroLivroISBN.getText();
        int edicao = Integer.valueOf(TxtRegistroLivroEdicao.getText());
        String autor = TxtRegistroLivroAutores.getText();
        String [] autores = autor.split(",");
        ArrayList<String> listaAutores = new ArrayList<>(Arrays.asList(autores));
        ArrayList<EnumGeneros> generos = new ArrayList<>();
        if(COMEDIA.isSelected()) generos.add(EnumGeneros.COMEDIA);
        if(DRAMA.isSelected()) generos.add(EnumGeneros.DRAMA);
        if(FANTASIA.isSelected()) generos.add(EnumGeneros.FANTASIA);
        if(THRILLER.isSelected()) generos.add(EnumGeneros.THRILLER);
        if(TERROR.isSelected()) generos.add(EnumGeneros.TERROR);
        if(ROMANCE.isSelected()) generos.add(EnumGeneros.ROMANCE);
        if(POLICIAL.isSelected()) generos.add(EnumGeneros.POLICIAL);
        if(DISTOPIA.isSelected()) generos.add(EnumGeneros.DISTOPIA);
        if(ACAO.isSelected()) generos.add(EnumGeneros.ACAO);
        if(AVENTURA.isSelected()) generos.add(EnumGeneros.AVENTURA);
        if(BIBLIOGRAFIA.isSelected()) generos.add(EnumGeneros.BIBLIOGRAFIA);
        if(AUTOAJUDA.isSelected()) generos.add(EnumGeneros.AUTOAJUDA);
        if(TRUECRIME.isSelected()) generos.add(EnumGeneros.TRUECRIME);
        if(DIDATICO.isSelected()) generos.add(EnumGeneros.DIDATICO);
       
        ControladorBiblioteca biblioteca = new ControladorBiblioteca(); //ajeitar isso aqui
        biblioteca.FazerRegistroLivro(titulo, listaAutores, edicao, ISBN, generos);
    }//GEN-LAST:event_BotaoRegistroLivroActionPerformed

    private void COMEDIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMEDIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COMEDIAActionPerformed

    private void DRAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DRAMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DRAMAActionPerformed

    private void ROMANCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ROMANCEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ROMANCEActionPerformed

    private void BIBLIOGRAFIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIBLIOGRAFIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BIBLIOGRAFIAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ACAO;
    private javax.swing.JCheckBox AUTOAJUDA;
    private javax.swing.JCheckBox AVENTURA;
    private javax.swing.JCheckBox BIBLIOGRAFIA;
    private javax.swing.JButton BotaoRegistroLivro;
    private javax.swing.JCheckBox COMEDIA;
    private javax.swing.JCheckBox DIDATICO;
    private javax.swing.JCheckBox DISTOPIA;
    private javax.swing.JCheckBox DRAMA;
    private javax.swing.JCheckBox FANTASIA;
    private javax.swing.JCheckBox POLICIAL;
    private javax.swing.JPanel PainelCadastroLeitor;
    private javax.swing.JCheckBox ROMANCE;
    private javax.swing.JCheckBox TERROR;
    private javax.swing.JCheckBox THRILLER;
    private javax.swing.JCheckBox TRUECRIME;
    private javax.swing.JTextField TxtRegistroLivroAutores;
    private javax.swing.JTextField TxtRegistroLivroEdicao;
    private javax.swing.JTextField TxtRegistroLivroISBN;
    private javax.swing.JTextField TxtRegistroLivroTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
