/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author Júlia
 */
public class TelaGerente extends javax.swing.JFrame {

    /**
     * Creates new form TelaGerente
     */
    public TelaGerente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuGerente = new javax.swing.JMenuBar();
        AbaContaGerente = new javax.swing.JMenu();
        AbaCadastrarFuncionarioGerente = new javax.swing.JMenu();
        AbaCancelarContaFuncionarioGerente = new javax.swing.JMenu();
        AbaFazerEmprestimo = new javax.swing.JMenu();
        AbaFazerDevolucao = new javax.swing.JMenu();
        AbaPagamentoMulta = new javax.swing.JMenu();
        AbaSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AbaContaGerente.setText("Conta");
        MenuGerente.add(AbaContaGerente);

        AbaCadastrarFuncionarioGerente.setText("Cadastrar funcionario");
        AbaCadastrarFuncionarioGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbaCadastrarFuncionarioGerenteActionPerformed(evt);
            }
        });
        MenuGerente.add(AbaCadastrarFuncionarioGerente);

        AbaCancelarContaFuncionarioGerente.setText("Cancelar conta de funcionário");
        MenuGerente.add(AbaCancelarContaFuncionarioGerente);

        AbaFazerEmprestimo.setText("Fazer empréstimo");
        MenuGerente.add(AbaFazerEmprestimo);

        AbaFazerDevolucao.setText("Fazer devolução");
        MenuGerente.add(AbaFazerDevolucao);

        AbaPagamentoMulta.setText("Fazer pagamento de multa");
        MenuGerente.add(AbaPagamentoMulta);

        AbaSair.setText("Sair");
        MenuGerente.add(AbaSair);

        setJMenuBar(MenuGerente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AbaCadastrarFuncionarioGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbaCadastrarFuncionarioGerenteActionPerformed
        // TODO add your handling code here:
        new TelaCadastroFuncionario().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_AbaCadastrarFuncionarioGerenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AbaCadastrarFuncionarioGerente;
    private javax.swing.JMenu AbaCancelarContaFuncionarioGerente;
    private javax.swing.JMenu AbaContaGerente;
    private javax.swing.JMenu AbaFazerDevolucao;
    private javax.swing.JMenu AbaFazerEmprestimo;
    private javax.swing.JMenu AbaPagamentoMulta;
    private javax.swing.JMenu AbaSair;
    private javax.swing.JMenuBar MenuGerente;
    // End of variables declaration//GEN-END:variables
}
