/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;
 
import Aplicacao.ControladorBiblioteca;
import javax.swing.JOptionPane;

/**
 *
 * @author Júlia
 */
public class TelaLoginFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaLoginFuncionario
     */
    public TelaLoginFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelLoginFuncionario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtLoginFuncionarioEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtLoginFuncionarioSenha = new javax.swing.JPasswordField();
        BotaoLoginFuncionario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loggar como Funcionario");
        setResizable(false);

        jLabel1.setText("Email");

        TxtLoginFuncionarioEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLoginFuncionarioEmailActionPerformed(evt);
            }
        });

        jLabel2.setText("Senha");

        TxtLoginFuncionarioSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLoginFuncionarioSenhaActionPerformed(evt);
            }
        });

        BotaoLoginFuncionario.setText("Entrar");
        BotaoLoginFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLoginFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelLoginFuncionarioLayout = new javax.swing.GroupLayout(PainelLoginFuncionario);
        PainelLoginFuncionario.setLayout(PainelLoginFuncionarioLayout);
        PainelLoginFuncionarioLayout.setHorizontalGroup(
            PainelLoginFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLoginFuncionarioLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(PainelLoginFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotaoLoginFuncionario)
                    .addGroup(PainelLoginFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtLoginFuncionarioEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                        .addComponent(TxtLoginFuncionarioSenha)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        PainelLoginFuncionarioLayout.setVerticalGroup(
            PainelLoginFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLoginFuncionarioLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtLoginFuncionarioEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtLoginFuncionarioSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(BotaoLoginFuncionario)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelLoginFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(PainelLoginFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtLoginFuncionarioEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLoginFuncionarioEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLoginFuncionarioEmailActionPerformed

    private void TxtLoginFuncionarioSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLoginFuncionarioSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLoginFuncionarioSenhaActionPerformed

    private void BotaoLoginFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLoginFuncionarioActionPerformed
        String texto = TxtLoginFuncionarioEmail.getText();
        String senha = String.valueOf(TxtLoginFuncionarioSenha.getPassword());
        ControladorBiblioteca biblioteca = new ControladorBiblioteca(); //ajeitar isso aqui
        if(biblioteca.FazerLoginFuncionario(texto, senha)){
            new TelaFuncionario().setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Acesso negado");
        }

    }//GEN-LAST:event_BotaoLoginFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLoginFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLoginFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLoginFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLoginFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLoginFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoLoginFuncionario;
    private javax.swing.JPanel PainelLoginFuncionario;
    private javax.swing.JTextField TxtLoginFuncionarioEmail;
    private javax.swing.JPasswordField TxtLoginFuncionarioSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
