/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Aplicacao.ControladorBiblioteca;
import java.time.LocalDate;
import java.time.Month;
import javax.swing.JOptionPane;

/**
 *
 * @author Júlia
 */
public class TelaCadastroLeitor extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroLeitor
     */
    public TelaCadastroLeitor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelCadastroLeitor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtCadastroLeitorNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        TxtCadastroLeitorEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtCadastroLeitorEndereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtCadastroLeitorTelefone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtCadastroLeitorCPF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtCadastroLeitorDia = new javax.swing.JTextField();
        TxtCadastroLeitorMes = new javax.swing.JTextField();
        TxtCadastroLeitorAno = new javax.swing.JTextField();
        TxtCadastroLeitorSenha = new javax.swing.JPasswordField();
        BotaoCadastroLeitor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar como leitor");
        setResizable(false);

        jLabel1.setText("Nome ");

        TxtCadastroLeitorNome.setText("Seu nome completo");
        TxtCadastroLeitorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCadastroLeitorNomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Endereco");

        jTextField2.setText("jTextField1");

        jLabel4.setText("Email");

        jLabel5.setText("Telefone");

        jLabel6.setText("CPF");

        jLabel7.setText("Senha");

        jLabel8.setText("Data de Nascimento");

        TxtCadastroLeitorDia.setText("Dia");
        TxtCadastroLeitorDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCadastroLeitorDiaActionPerformed(evt);
            }
        });

        TxtCadastroLeitorMes.setText("Mês");
        TxtCadastroLeitorMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCadastroLeitorMesActionPerformed(evt);
            }
        });

        TxtCadastroLeitorAno.setText("Ano");

        BotaoCadastroLeitor.setText("Cadastrar");
        BotaoCadastroLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastroLeitorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelCadastroLeitorLayout = new javax.swing.GroupLayout(PainelCadastroLeitor);
        PainelCadastroLeitor.setLayout(PainelCadastroLeitorLayout);
        PainelCadastroLeitorLayout.setHorizontalGroup(
            PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastroLeitorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCadastroLeitorTelefone)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelCadastroLeitorLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCadastroLeitorNome, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(TxtCadastroLeitorEmail)
                    .addComponent(TxtCadastroLeitorEndereco)
                    .addComponent(TxtCadastroLeitorCPF)
                    .addGroup(PainelCadastroLeitorLayout.createSequentialGroup()
                        .addComponent(TxtCadastroLeitorDia, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtCadastroLeitorMes, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtCadastroLeitorAno, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TxtCadastroLeitorSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(BotaoCadastroLeitor)
                .addGap(21, 21, 21))
            .addGroup(PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PainelCadastroLeitorLayout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(122, Short.MAX_VALUE)))
        );
        PainelCadastroLeitorLayout.setVerticalGroup(
            PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastroLeitorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtCadastroLeitorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtCadastroLeitorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtCadastroLeitorEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtCadastroLeitorTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtCadastroLeitorCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCadastroLeitorDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCadastroLeitorMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCadastroLeitorAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCadastroLeitorSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoCadastroLeitor))
                .addGap(13, 13, 13))
            .addGroup(PainelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PainelCadastroLeitorLayout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(310, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelCadastroLeitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCadastroLeitorDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCadastroLeitorDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCadastroLeitorDiaActionPerformed

    private void TxtCadastroLeitorMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCadastroLeitorMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCadastroLeitorMesActionPerformed

    private void TxtCadastroLeitorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCadastroLeitorNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCadastroLeitorNomeActionPerformed

    private void BotaoCadastroLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastroLeitorActionPerformed
        // TODO add your handling code here:
        String nome = TxtCadastroLeitorNome.getText();
        String email = TxtCadastroLeitorEmail.getText();
        String endereco = TxtCadastroLeitorEndereco.getText();
        String telefone = TxtCadastroLeitorTelefone.getText();
        String CPF = TxtCadastroLeitorCPF.getText();
        String senha = String.valueOf(TxtCadastroLeitorSenha.getPassword());
        int dia = Integer.parseInt(TxtCadastroLeitorDia.getText());
        int mes = Integer.parseInt(TxtCadastroLeitorMes.getText());
        int ano = Integer.parseInt(TxtCadastroLeitorAno.getText());
        LocalDate dataNascimento = LocalDate.of(ano, mes, dia);
        ControladorBiblioteca biblioteca = new ControladorBiblioteca(); //ajeitar isso aqui
        if(biblioteca.FazerCadastroLeitor(nome, email, CPF, senha, telefone, endereco, dataNascimento)){
            new TelaLeitor().setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "O cadastro não pode ser concluído");
        }
    }//GEN-LAST:event_BotaoCadastroLeitorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroLeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroLeitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastroLeitor;
    private javax.swing.JPanel PainelCadastroLeitor;
    private javax.swing.JTextField TxtCadastroLeitorAno;
    private javax.swing.JTextField TxtCadastroLeitorCPF;
    private javax.swing.JTextField TxtCadastroLeitorDia;
    private javax.swing.JTextField TxtCadastroLeitorEmail;
    private javax.swing.JTextField TxtCadastroLeitorEndereco;
    private javax.swing.JTextField TxtCadastroLeitorMes;
    private javax.swing.JTextField TxtCadastroLeitorNome;
    private javax.swing.JPasswordField TxtCadastroLeitorSenha;
    private javax.swing.JTextField TxtCadastroLeitorTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
