/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;
import Aplicacao.ControladorBiblioteca;

import javax.swing.JOptionPane;

/**
 *
 * @author Júlia
 */
public class TelaLoginLeitor extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLoginLeitor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelLoginLeitor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtLoginLeitorEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtLoginLeitorSenha = new javax.swing.JPasswordField();
        BotaoLoginLeitor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loggar como Leitor");
        setResizable(false);

        jLabel1.setText("Email");

        TxtLoginLeitorEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLoginLeitorEmailActionPerformed(evt);
            }
        });

        jLabel2.setText("Senha");

        TxtLoginLeitorSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLoginLeitorSenhaActionPerformed(evt);
            }
        });

        BotaoLoginLeitor.setText("Entrar");
        BotaoLoginLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLoginLeitorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelLoginLeitorLayout = new javax.swing.GroupLayout(PainelLoginLeitor);
        PainelLoginLeitor.setLayout(PainelLoginLeitorLayout);
        PainelLoginLeitorLayout.setHorizontalGroup(
            PainelLoginLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLoginLeitorLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(PainelLoginLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotaoLoginLeitor)
                    .addGroup(PainelLoginLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtLoginLeitorEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                        .addComponent(TxtLoginLeitorSenha)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        PainelLoginLeitorLayout.setVerticalGroup(
            PainelLoginLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLoginLeitorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtLoginLeitorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtLoginLeitorSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(BotaoLoginLeitor)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelLoginLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(PainelLoginLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtLoginLeitorEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLoginLeitorEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLoginLeitorEmailActionPerformed

    private void TxtLoginLeitorSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLoginLeitorSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLoginLeitorSenhaActionPerformed

    private void BotaoLoginLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLoginLeitorActionPerformed
        String texto = TxtLoginLeitorEmail.getText();
        String senha = String.valueOf(TxtLoginLeitorSenha.getPassword());
        ControladorBiblioteca biblioteca = new ControladorBiblioteca(); //ajeitar isso aqui
        if(biblioteca.FazerLoginLeitor(texto, senha)){
            new TelaLeitor().setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Acesso negado");
        }
        
    }//GEN-LAST:event_BotaoLoginLeitorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLoginLeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLoginLeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLoginLeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLoginLeitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLoginLeitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoLoginLeitor;
    private javax.swing.JPanel PainelLoginLeitor;
    private javax.swing.JTextField TxtLoginLeitorEmail;
    private javax.swing.JPasswordField TxtLoginLeitorSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
